### ISSUE TITLE
Server Sending Invalid Match Key Parameters for Search Event

### ISSUE THREAD

**Issue by aaronlax** [digitalwithyou/craft-facebook-conversion#25]
"Your server is sending an invalid fbp, ip_address parameters value for your Search event. This may be because there was an error in the parameter value."

Not sure how to troubleshoot this, was reported by the site owner

**Comment by Diewy** [comment]
Hi @aaronlax,

That error can be caused by differentent reasons, it can get difficult to find the exact reason.

- That error can be triggered by bots or scripts. So, when it's not showing for all events, it can safely be ignored.
- Can PHP read the correct IP Address of the user? If not, that can give a mismatch. E.g. the webserver is hosted by AWS or is beyond a load balancer.

Does that help?

**Comment by mostafasoufi** [comment]
The same issue!

Shouldn't be sent those event's parameters into the custom parameters? https://github.com/digitalwithyou/craft-facebook-conversion/blob/main/src/listeners/cms/Search.php#L14

@Diewy
