### ISSUE TITLE
Search event doesn't compatible with live search

### ISSUE THREAD

**Issue by mostafasoufi** [digitalwithyou/craft-facebook-conversion#26]
Considering that typing on the search box triggers a search event, it makes sense that it wouldn't be compatible, but I'm curious to know your thoughts on this.

https://capture.dropbox.com/YiDHcFYI34opV4am

**Comment by Diewy** [comment]
Hmm, in this case it might be better to have the clicked result (product name) to be send as an event. So 1x "Grant JB Nova Water Bath, 12L" instead of 4 events typing "simple pro".
Or to send the final search term when clicking a result. So 1x "simple prod".

For both you would have to capture the click event on the result and send the event before navigating to the new url. (Btw, use `sendBeacon` or the `keepalive` property on the `fetch` method, [more info](https://www.stefanjudis.com/today-i-learned/fetch-supports-a-keepalive-option-to-make-it-outlive-page-navigations/))

But if there is a marketeer working on the project, ask him/her which events would be the most useful.
