### ISSUE TITLE
SDK should update to latest version.

### ISSUE THREAD

**Issue by mostafasoufi** [digitalwithyou/craft-facebook-conversion#27]
According to the reference ([#9a7f6](https://github.com/digitalwithyou/craft-facebook-conversion/blob/main/composer.lock#L1468)), there is an issue behind the reference, and the SDK should be updated to the latest commit.

https://github.com/facebook/facebook-php-business-sdk/commits/main

**Comment by Diewy** [comment]
Hi @mostafasoufi,

We're using the latest [package version](https://packagist.org/packages/facebook/php-business-sdk), currently v15. I see that I made a [typo](https://github.com/digitalwithyou/craft-facebook-conversion/commit/9706d943004a8fad8bb722ba3f69ba9092a31a7f), v14 instead of v15, in the commit message (woops), but the composer.json file is changed correctly.

I don't think it would be a good idea to start using `dev-main` without any special reason.

**Comment by mostafasoufi** [comment]
Actually, It's not the dev-main and you still need to update the `composer.lock` 🙂

![Screenshot 2022-10-31 at 6 00 33 PM](https://user-images.githubusercontent.com/701520/199032403-0b3d11ae-be38-41f3-b516-776a93d72625.png)
